### ISSUE TITLE
Hackathon log

### ISSUE THREAD

**Issue by keitakawamoto** [balloonbros/sutekki#4]
:busts_in_silhouette::sweat_drops:

**Comment by keitakawamoto** [comment]
### 5/21
- トップ構成
- 記事一覧構成

**Comment by shoyan** [comment]
### 5/21
- [x] 雛形つくる
- [x] 記事を投稿できるようにする

**Comment by keitakawamoto** [comment]
とりあえずフォームのスタイルを用意した。

![image](https://cloud.githubusercontent.com/assets/1661325/7748558/a0515e50-0000-11e5-8829-3634971dcba3.png)

次回は引き続き以下
- トップ構成
- 記事一覧構成

**Comment by shoyan** [comment]
@keitakawamoto ナイス :+1:

**Comment by shoyan** [comment]
### 次回やること
- [x] ベーシック認証かける
- [x] ラベルのリソースセットを作成する
- [x] 記事とラベルのアソシエーション

**Comment by shoyan** [comment]
### 次回やること
- [x] アイデアのタイトルは不要なので消す
- [x] Publishedはデフォルトでtrue
- [x] アイデアに関連するタグを表示する
- [x] タグに関連するアイデアの一覧ページを作成

URLはこんな感じ
http://mark0.com/labels/ラベル名

**Comment by keitakawamoto** [comment]
タイトルは不要であることに今回気づいた。

今回トップ構成をここまで作った。
wiki記事とメモ記事についての仕組みをまだ固めて切っていないが、メモはこのようにトップ画面でタイムライン状に流れてくる。

![mark-0](https://cloud.githubusercontent.com/assets/1661325/7882625/6f1dec04-064a-11e5-81a0-b5a5ded17d7f.png)

**まずはメモをこのように流せるところを目標に作る**

**Comment by keitakawamoto** [comment]
### 次回やること
- 現状をひとまずコーディング

**Comment by keitakawamoto** [comment]
## 使い始めるタイミング
- タグをつけれる
- タグで絞り込める
- cssが当たっている

上記を満たしたらHerokuにアップロードし利用開始する。

**Comment by shoyan** [comment]
### 次回やること
- [x] 関連づけされているラベルの表示
- [x] フォームのtitleを復活させる
- ~~[ ] ラベルをアイデアにつけれるようにする~~

**Comment by keitakawamoto** [comment]
### 次回やること
- [x] スタイルを当てていく

**Comment by keitakawamoto** [comment]
### 次回やること
- [x] スタイルを当てていく
- [x] post一覧を個別に枠を付けるのではなく、一覧自体で括る（postごとの区切りは `border-bottom` にする）

**Comment by shoyan** [comment]
### 次回やること
- [x] アイデアにラベルをつけれるようにする
- [x] アイデアは新しい順に並べる
- [x] TOPにラベル作成のリンクをつける

**Comment by keitakawamoto** [comment]
OOCSS,SMACSSを意識

**Comment by keitakawamoto** [comment]
## 使用開始

ある程度の昨日とcssが適用され、Herokuにアップロードしたので利用開始！ :sushi:

**Comment by shoyan** [comment]
### 次回やること
- ~~[ ] ユーザー登録機能~~
- [x] Slack通知
- ~~[ ] コメントをつける~~
- ~~[ ] 投稿時にタグを登録~~

**Comment by keitakawamoto** [comment]
## 次回やること
- ~~[ ] タグ周りのスタイル適用~~
- ~~[ ] 新規投稿フォームをラベル・入力フォームを一体化させる。~~
  - 参考：http://coliss.com/articles/build-websites/architectonics/usability/decrease-form-abandonment-by-uxmovement.html

**Comment by keitakawamoto** [comment]
## 割り込み
- wiki化について詰める
- deleteとは別にメモのopen/closeステータスも必要

**Comment by shoyan** [comment]
### 2015/7/14のハッカソンでやったこと
- [x] [Slack通知](https://github.com/balloonbros/wiki-tool/pull/8)

### 次回やること
- [x] Slack通知（メッセージの折りたたみ）
- [x]  ユーザー登録機能
- [x]  コメントをつける
- [x]  投稿時にタグを登録

**Comment by keitakawamoto** [comment]
### 進捗

![image](https://cloud.githubusercontent.com/assets/1661325/8672655/83c45ea0-2a6b-11e5-8611-4bcecff624d4.png)

### 検討事項
- Wikiって言葉わかりにくい？
- Idea（メモ）とWiki（まとめ/ノート）って言い方について検討
- `アイデア` と `ノート` ？

### 次回やること
- ~~[ ] Wiki化構想~~

**Comment by keitakawamoto** [comment]
名称はいまのところ `メモ` と `まとめ`。
一番ストレートで的確でわかりやすい。

**Comment by keitakawamoto** [comment]
https://github.com/balloonbros/sutekki/pull/15
ここで通知を改善。 @shoyan  作のSlack-incoming-webhooksを利用。

**Comment by keitakawamoto** [comment]
途切れたのでこのissueは閉じる
